#!/bin/bash
. "$(dirname "${BASH_SOURCE}")/lib/bootstrap.sh"
. "$(dirname "${BASH_SOURCE}")/lib/utils.sh"


# ===== Constants and functions


function main() {
    local test_report_export_root_path="$1"

    mkdir --parents "${test_report_export_root_path}"

    local failed_commands_count=0
    for docker_compose_file_path in $(find "$(get_project_root_path)" -name testing.dc.yml); do
        local image_short_name="$(basename "$(dirname "${docker_compose_file_path}")")"
        local test_report_export_path="${test_report_export_root_path}/${image_short_name}"

        if ! ddu-test-image "${docker_compose_file_path}" "${test_report_export_path}"; then
            failed_commands_count=$((failed_commands_count + 1))
        fi
    done

    [[ ${failed_commands_count} == 0 ]]
}


# ===== Main


TEST_REPORT_EXPORT_ROOT_PATH="$1"

main "${TEST_REPORT_EXPORT_ROOT_PATH}"
