#!/bin/bash
. "$(dirname "${BASH_SOURCE}")/lib/bootstrap.sh"


echo 'Deleting stale containers'
docker ps -a --format '{{.ID}} {{.Status}}' | grep -v ' Up ' | awk '{ print $1 }' | xargs --no-run-if-empty docker rm --force --volumes

echo

echo 'Deleting anonymous images'
docker images | grep '<none>' | awk '{ print $3 }' | xargs --no-run-if-empty docker rmi

echo

echo "Deleting dangling volumes"
docker volume ls --filter=dangling=true | grep '^local' | awk '{ print $2 }' | xargs docker volume rm
