#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail


# ===== Constants and functions


function usage {
    echo "Usage: ${0##*/} run|up|down|build [EXTRA_ARGS...]" >&2
    exit 1
}


# ===== Main


if [[ "$#" == "0" ]]; then
    usage
fi
SUBCOMMAND="$1"
SUBCOMMAND_ARGS="${@:2}"  # TODO: Does NOT work with args containing spaces

case "${SUBCOMMAND}" in
    run)
        exec docker-compose run --rm ${SUBCOMMAND_ARGS}
        ;;
    up)
        exec docker-compose up \
            --force-recreate \
            --abort-on-container-exit \
            --remove-orphans \
            ${SUBCOMMAND_ARGS}
        ;;
    down)
        exec docker-compose down \
            --rmi local \
            --volumes \
            --remove-orphans \
            ${SUBCOMMAND_ARGS}
        ;;
    build)
        exec docker-compose build --force-rm --pull ${SUBCOMMAND_ARGS}
        ;;
    *)
        usage
        ;;
esac
